# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

  # 数据库配置 - 生产环境
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 生产环境连接池配置优化
      maximum-pool-size: 50                # 根据服务器配置调整
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      pool-name: SpringBootProdHikariCP

  # JPA 配置 - 生产环境
  jpa:
    hibernate:
      ddl-auto: validate                   # 生产环境只验证，不自动更新
    show-sql: false                        # 生产环境不显示 SQL
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
        jdbc.batch_size: 50                 # 生产环境批处理大小调大
        order_inserts: true
        order_updates: true
        jdbc.fetch_size: 200
        # 生产环境二级缓存配置（预留）
        cache:
          use_second_level_cache: false     # 暂时关闭二级缓存
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        # 生产环境统计信息
        generate_statistics: false

  # Flyway 配置 - 生产环境
  flyway:
    clean-disabled: true                  # 生产环境禁止 clean
    validate-on-migrate: true
    baseline-on-migrate: true
    placeholder-replacement: true

  # Redis 配置 - 生产环境
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: 5000                         # 生产环境超时时间缩短
      lettuce:
        pool:
          max-active: 100                    # 生产环境连接池调大
          max-idle: 50
          min-idle: 10
          max-wait: 5000
          time-between-eviction-runs: 30000   # 回收间隔缩短

  # 缓存配置 - 生产环境
  cache:
    type: redis                            # 生产环境使用 Redis 缓存
    cache-names: user,role,permission,api_response,menu,config
    redis:
      time-to-live: 600000                 # 默认 10 分钟
      cache-null-values: false              # 不缓存空值

  # JSON 配置 - 生产环境
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

# 日志配置 - 生产环境
logging:
  level:
    root: WARN                           # 生产环境根日志级别为 WARN
    com.example.demo: INFO               # 项目日志级别为 INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.cache: INFO
    org.springframework.data.redis: WARN
  file:
    name: logs/prod/springboot-starter-prod.log
    max-size: 50MB                       # 生产环境日志文件大小调大
    max-history: 90
    total-size-cap: 10GB
    clean-history-on-start: true
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 10GB
      file-name-pattern: logs/prod/springboot-starter-prod.%d{yyyy-MM-dd}.%i.log.gz

# 生产环境管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        liveness:
          include: db,redis
        readiness:
          include: db,redis
    env:
      keys-to-sanitize: password,secret,key,token,credential  # 敏感信息脱敏
    info:
      git:
        mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: springboot-starter
      environment: production
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5,0.95,0.99,0.999

# 生产环境安全配置
app:
  security:
    debug: false                         # 关闭调试模式
    allow-paths: /api/auth/**,/actuator/health,/actuator/info
  cors:
    allowed-origins: "${ALLOWED_ORIGINS:}"  # 生产环境配置允许的域名
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,Accept,X-Requested-With
    allow-credentials: true
    max-age: 3600

# 生产环境文件上传配置
app:
  upload:
    path: ${UPLOAD_PATH:/data/uploads}     # 生产环境上传路径
    max-size: 52428800                   # 50MB
  file:
    storage-type: ${FILE_STORAGE_TYPE:local}
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar
    max-file-size: 52428800               # 50MB

# 生产环境性能优化
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/css,application/javascript,text/plain,application/font-woff,application/font-woff2
    min-response-size: 2048
  tomcat:
    max-threads: 200                     # 最大线程数
    min-spare-threads: 20                # 最小空闲线程数
    accept-count: 100                    # 等待队列长度
    connection-timeout: 20000            # 连接超时时间
    max-connections: 10000               # 最大连接数

# 生产环境监控配置
management:
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: springboot-starter
      profile: prod
  tracing:
    sampling:
      probability: 0.1                  # 采样率 10%

# 生产环境健康检查配置
management:
  health:
    redis:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10MB                    # 磁盘空间阈值
    ping:
      enabled: true